name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: echo "Hello, world!"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm # adjust if not Node
          key: cache-dd4245f

      - name: prime-cache-dd4245f
        run: echo "Cache result: ${{ steps.cache.outputs.cache-hit }}"

      - name: Install deps
        run: npm install
